#!/bin/bash

pExtract=xf

if [[ "$*" == *.gz ]]; then
  pExtract=xzf
elif [[ "$*" == *.xz ]]; then
  pExtract=xJf
fi

if [[ ! -d "$1.unpacked" ]]; then
	mkdir "$1.unpacked"
fi

cd "$1.unpacked"
tar "-$pExtract" "../$1"
cd -



