#!/bin/bash

params=xf
prms=cf

if [[ "$*" == *.gz ]]; then
  params=xzf
  prms=czf
elif [[ "$*" == *.xz ]]; then
  params=xJf
  prms=cJf
fi

if [[ ! mkdir "$1.unpacked" ]]; then
	mkdir "$1.unpacked"
fi

#echo "$*"
#echo "$params"
tar "-$params" "$*"
tar "-$prms" "$*.unpacked" some


